### PR TITLE
Fixes for import weirdness

### LINKED ISSUE #66: TypeScript import weirdness
From Zelo101#0138 on the Antimatter Dimensions Discord server in the game-dev channel:

> I've got this error with `AD-notations`, does anyone know how to solve this?
> Screenshot of error log
> ...
> here is how i import it
> Screenshot of how `break_infinity.js` is imported

(Note: This will be the tracking issue to fix the package entry-points)

### PR DESCRIPTION
**Pull request by EdricChan03**
This PR also improves how the declaration files are actually generated by specifying the `include` field in `tsconfig.json`.

Closes #66

### CODE REVIEW

**Comment by EdricChan03** [comment]
(Sidenote: The `pad-end` package shim should probably be removed as we can also specify the `lib` field in `tsconfig.json`'s `compilerOptions` field:

```json
{
  "compilerOptions": {
    // ...
    "lib": [
      "ES2017.String"
    ]
  }
```

This'll be done in a future PR to clean up any remaining required dependencies.

**Comment by Razenpok** [comment]
LGTM

Can't we just rename break_infinity.ts to index.ts?

**Comment by EdricChan03** [comment]
> LGTM

Sidenote: Could you use the [review function for GitHub PRs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews) instead of a comment?

> Can't we just rename break_infinity.ts to index.ts?

Come to think of it I should've done that

**Comment by EdricChan03** [comment]
> Epic. I'll merge this PR and wait for the pad-end one before rolling out a new release.

Hmm, it seems that the `lib` thing doesn't include polyfills as documented in a comment by [Dmitrii Sorin](https://stackoverflow.com/questions/39303385/what-does-the-tsconfig-option-lib-do#comment90063851_39306295):

> Beware that including "es2015.promise" or whatsoever doesn't include a polyfill into your compiled code. Instead you just notify the compiler that your code is using promises and it should be okay with that. If you need to add promises polyfills, consider either importing the polyfill in your code or using babel with corresponding machinery (babel-preset-env) as a post-step (or next loader in webpack)

I guess there's not really a way to do it without introducing an external dependency 🤷‍♂️

**Comment by Razenpok** [comment]
Hey @Patashu, should we just yeet the polyfill? It's 95% supported already.

**Comment by Patashu** [comment]
As long as people are still using IE11 I'd like break_infinity.js to remain IE11 compatibility unless doing so makes you tear your hair out, and this just sounds like a 'well it'd be nice'.

**Comment by Razenpok** [comment]
Aight, I'm publishing a new release then

**Pull request merged**
